Hckrieger/Pages/Categories/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hckrieger.Pages.Categories
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly Hckrieger.Data.ApplicationDbContext _context;

        public DeleteModel(Hckrieger.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FirstOrDefaultAsync(m => m.CategoryId == id);

            if (category == null)
            {
                return NotFound();
            }
            else 
            {
                Category = category;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }
            var category = await _context.Categories.FindAsync(id);

            if (category != null)
            {
                Category = category;
                _context.Categories.Remove(Category);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Hckrieger/Pages/Categories/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hckrieger.Pages.Categories
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly Hckrieger.Data.ApplicationDbContext _context;

        public DetailsModel(Hckrieger.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Category Category { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            else 
            {
                Category = category;
            }
            return Page();
        }
    }
}

Hckrieger/Pages/Categories/Upsert.cshtml.cs
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hckrieger.Pages.Categories
{
    [Authorize]
    public class UpsertModel : PageModel
    {
        private readonly ApplicationDbContext db;




        public UpsertModel(ApplicationDbContext db)
        {
            this.db = db;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            Category = new Category();
            if (id == null)
            {
                return Page();
            }

            Category = await db.Categories.FirstOrDefaultAsync(m => m.CategoryId == id);

            if (Category == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Category.CategoryId == 0)
                {
                    db.Categories.Add(Category);
                }
                else
                {
                    db.Categories.Update(Category);
                }
                await db.SaveChangesAsync();
                return RedirectToPage("Index");
            }

            return Page();
        }
    }
}

Hckrieger/Pages/Posts/Archives.cshtml.cs
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hckrieger.Pages.Posts
{
    public class ArchivesModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public ArchivesModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Post> Posts { get; set; }

        public async Task OnGetAsync()
        {
            Posts = await _context.Posts
                .OrderByDescending(m => m.PostId)
                .Where(m => m.Visible)
                .AsNoTracking()
                .ToListAsync();
        }
    }
}

Hckrieger/Pages/Posts/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hckrieger.Pages.Posts
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly Hckrieger.Data.ApplicationDbContext _context;

        public DeleteModel(Hckrieger.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Post Post { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FirstOrDefaultAsync(m => m.PostId == id);

            if (post == null)
            {
                return NotFound();
            }
            else 
            {
                Post = post;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }
            var post = await _context.Posts.FindAsync(id);

            if (post != null)
            {
                Post = post;
                _context.Posts.Remove(Post);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Hckrieger/Pages/Posts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Hckrieger.Data;
using Hckrieger.Models;

namespace Hckrieger.Pages.Posts
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public Post Post { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Post = await _context.Posts
                .Include(p => p.PostCategory)
                .ThenInclude(p => p.Category)
                .Include(p => p.PostTag)
                .ThenInclude(p => p.Tag)
                .FirstOrDefaultAsync(m => m.PostId == id);

            if (Post == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Hckrieger/Pages/Posts/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hckrieger.Pages.Posts
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Post> Post { get; set; }

        public async Task OnGetAsync()
        {
            Post = await _context.Posts
                .OrderByDescending(m => m.PostId)
                .AsNoTracking()
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostVisibility(int id)
        {
            var post = await _context.Posts.FindAsync(id);

            if (post == null)
            {
                return NotFound();
            }

            if (!post.Visible)
            {
                post.Visible = true;
            } else
            {
                post.Visible = false;
            }

            _context.Update(post);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");   
        }
    }
}

Hckrieger/Pages/Posts/ManageCategories.cshtml.cs
using Hckrieger.Data;
using Hckrieger.Models;
using Hckrieger.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hckrieger.Pages.Posts
{
    [Authorize]
    public class ManageCategoriesModel : PageModel
    {
        private readonly ApplicationDbContext db;

        public ManageCategoriesModel(ApplicationDbContext db)
        {
            this.db = db;
        }

        [BindProperty]
        public PostCategoryVM PostCategoryVM { get; set; }

        public async Task<IActionResult> OnGet(int id)
        {
            PostCategoryVM = new PostCategoryVM
            {
                PostCategoryList = await db.PostCategories.Include(u => u.Category)
                                               .Include(u => u.Post)
                                               .Where(u => u.PostId == id).ToListAsync(),
                PostCategory = new PostCategory()
                {
                    PostId = id
                },
                Post = await db.Posts.FirstOrDefaultAsync(u => u.PostId == id)
            };

            List<int> tempListOfAssignedCategories = PostCategoryVM.PostCategoryList.Select(i => i.CategoryId).ToList();
            var categoryList = db.Categories.Where(u => !tempListOfAssignedCategories.Contains(u.CategoryId)).OrderBy(m => m.Name);

            PostCategoryVM.CategoryList = categoryList.Select(i => new SelectListItem()
            {
                Text = i.Name,
                Value = i.CategoryId.ToString()
            });


            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (PostCategoryVM.PostCategory.PostId != 0 && PostCategoryVM.PostCategory.CategoryId != 0)
            {
                db.PostCategories.Add(PostCategoryVM.PostCategory);
                await db.SaveChangesAsync();
            }

            return RedirectToPage(new { @id = PostCategoryVM.PostCategory.PostId });
        }

        public async Task<IActionResult> OnPostDelete(int categoryId)
        {
            int postId = PostCategoryVM.Post.PostId;

            if (postId == 0)
            {
                return NotFound();
            }

            PostCategory PostCategoryToRemove = await db.PostCategories.FirstOrDefaultAsync(u => u.PostId == postId && u.CategoryId == categoryId);

            db.PostCategories.Remove(PostCategoryToRemove);
            await db.SaveChangesAsync();

            return RedirectToPage(new { @id = postId });
        }
    }
}

Hckrieger/Pages/Posts/ManageTags.cshtml.cs
using Hckrieger.Data;
using Hckrieger.Models;
using Hckrieger.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hckrieger.Pages.Posts
{
    [Authorize]
    public class ManageTagsModel : PageModel
    {
        private readonly ApplicationDbContext db;

        public ManageTagsModel(ApplicationDbContext db)
        {
            this.db = db;
        }

        [BindProperty]
        public PostTagVM PostTagVM { get; set; }

        public async Task<IActionResult> OnGet(int id)
        {
            PostTagVM = new PostTagVM
            {
                PostTagList = await db.PostTags.Include(u => u.Tag)
                                               .Include(u => u.Post)
                                               .Where(u => u.PostId == id).ToListAsync(),
                PostTag = new PostTag()
                {
                    PostId = id
                },
                Post = await db.Posts.FirstOrDefaultAsync(u => u.PostId == id)
            };

            List<int> tempListOfAssignedTags = PostTagVM.PostTagList.Select(i => i.TagId).ToList();
            var tagList = db.Tags.Where(u => !tempListOfAssignedTags.Contains(u.TagId)).OrderBy(m => m.Name);

            PostTagVM.TagList = tagList.Select(i => new SelectListItem()
            {
                Text = i.Name,
                Value = i.TagId.ToString()
            });


            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (PostTagVM.PostTag.PostId != 0 && PostTagVM.PostTag.TagId != 0)
            {
                db.PostTags.Add(PostTagVM.PostTag);
                await db.SaveChangesAsync();
            }

            return RedirectToPage(new { @id = PostTagVM.PostTag.PostId });
        }

        public async Task<IActionResult> OnPostDelete(int tagId)
        {
            int postId = PostTagVM.Post.PostId;

            if (postId == 0)
            {
                return NotFound();
            }

            PostTag PostTagToRemove = await db.PostTags.FirstOrDefaultAsync(u => u.PostId == postId && u.TagId == tagId);

            db.PostTags.Remove(PostTagToRemove);
            await db.SaveChangesAsync();

            return RedirectToPage(new { @id = postId });
        }
    }
}

Hckrieger/Pages/Posts/Upsert.cshtml.cs
using Hckrieger.Data;
using Hckrieger.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hckrieger.Pages.Posts
{
    [Authorize]
    public class UpsertModel : PageModel
    {
        private readonly ApplicationDbContext db;


        public UpsertModel(ApplicationDbContext db)
        {
            this.db = db;
        }

        [BindProperty]
        public PostVM PostVM { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            PostVM = new PostVM();

            if (id == null)
            {
                return Page();
            }

            PostVM.Post = await db.Posts.FirstOrDefaultAsync(m => m.PostId == id);

            if (PostVM.Post == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                if (PostVM.Post.PostId == 0)
                {
                    db.Posts.Add(PostVM.Post);
                }
                else
                {
                    db.Posts.Update(PostVM.Post);
                }

                await db.SaveChangesAsync();

            }

            return RedirectToPage("Index");
        }
    }
}

Hckrieger/Pages/Tags/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Hckrieger.Data;
using Hckrieger.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hckrieger.Pages.Tags
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly Hckrieger.Data.ApplicationDbContext _context;

        public DeleteModel(Hckrieger.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Tag Tag { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FirstOrDefaultAsync(m => m.TagId == id);

            if (tag == null)
            {
                return NotFound();
            }
            else 
            {
                Tag = tag;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }
            var tag = await _context.Tags.FindAsync(id);

            if (tag != null)
            {
                Tag = tag;
                _context.Tags.Remove(Tag);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Hckrieger/Pages/Posts/Archives.cshtml
@page
@model Hckrieger.Pages.Posts.ArchivesModel
@{
    ViewData["Title"] = "Posts";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Posts</h1>

<div class="row post-archives">
    @if (Model.Posts.Count > 0)
    {
        @foreach (var item in Model.Posts)
        {
            <div class="col-lg-6">

                <div class="post post-@item.PostId">

                    <h5>Hunter Krieger</h5>
                    <h3><a asp-page="/Posts/Details" asp-route-id="@item.PostId">@item.Title</a></h3>
                    <h5>@item.DatePublished</h5>
                </div>
            </div>

        }
    } else
    {
        <h5 class="mt-3 text-center">
            Sorry, there are no posts right now.  Check back later.
        </h5>
    }


</div><br />

Hckrieger/Pages/Posts/Delete.cshtml
@page
@model Hckrieger.Pages.Posts.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Post.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Post.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Post.DatePublished)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Post.DatePublished)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Post.Content)
        </dt>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Post.PostId" />
        <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you really REALLY sure you want to delete this?')" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Hckrieger/Pages/Posts/Details.cshtml
@page
@model Hckrieger.Pages.Posts.DetailsModel

@{
    ViewData["Title"] = Html.DisplayFor(m => m.Post.Title);
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@if (User.Identity.IsAuthenticated)
{
    <div>
        <a class="btn btn-md btn-info" asp-page="./Upsert" asp-route-id="@Model.Post.PostId">Edit</a> 
        <a class="btn btn-md btn-info" asp-page="./Index">Back to List</a>
    </div>
   <hr />
}

<article class="post post-@Model.Post.PostId">
    <div class="post-header">
        <h6>@Html.DisplayFor(m => m.Post.DatePublished)</h6>
        <h2>@Html.DisplayFor(m => m.Post.Title)</h2>
        <h5>By Hunter Krieger</h5>
        @if (Model.Post.PostCategory?.Count > 1)
        {
            <h6>Categories: 

                
                    @foreach(var item in Model.Post.PostCategory)
                    {
                        <span>@item.Category?.Name</span>
                        if (@item.Category?.CategoryId != Model.Post.PostCategory.Last().CategoryId)
                        {
                            <span style="margin-left: -5px;">, </span>
                        }
                    }
                

            </h6>
        } else if (Model.Post.PostCategory?.Count == 1)
        {
            <h6>Category: @Html.DisplayFor(m => m.Post.PostCategory.First().Category.Name)</h6>
        } 
        
    </div>
    <hr />
    <div class="post-content">
        @Html.Raw(Model.Post.Content)
    </div>
    @if (Model.Post.PostTag?.Count > 0)
    {
        <hr />
        <div class="tags">
            <h5>
                <strong>tags: </strong>
            </h5>

            @foreach (var item in Model.Post.PostTag.OrderBy(m => m.Tag?.Name))
            {
                <p>@item.Tag?.Name</p>
            }
        </div>
    }
</article>
<br />
<h5 class="text-center">
    <a asp-page="Details" asp-route-id="@Model.Post.PostId">back to top</a>
</h5>

Hckrieger/Pages/Posts/Index.cshtml
@page
@model Hckrieger.Pages.Posts.IndexModel
@using System.Text.RegularExpressions;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<partial name="~/Pages/Shared/_BlogNavPartial.cshtml" />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Post[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Post[0].DatePublished)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Post)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatePublished)
                </td>
                <td>
                    <form method="post" style="display: inline">
                        @if (!item.Visible)
                        {
                            <span style="color: darkred;">Hidden</span>
                            <span> - </span>
                            <button asp-page-handler="Visibility" asp-route-id=@item.PostId class="link-primary" style="font-size: 13px;">
                                Show
                            </button> <span>|</span>
                        } else
                        {
                            <span style="color: darkgreen">Visible</span>
                            <span> - </span>
                            <button asp-page-handler="Visibility" asp-route-id=@item.PostId class="link-primary" style="font-size: 13px;">
                                Hide
                            </button> <span>|</span>
                        }
                    </form>

                    <a asp-page="./ManageCategories" asp-route-id="@item.PostId">Categories</a> |
                    <a asp-page="./ManageTags" asp-route-id="@item.PostId">Tags</a> |
                    <a asp-page="./Upsert" asp-route-id="@item.PostId">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.PostId">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.PostId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Hckrieger/Pages/Posts/ManageCategories.cshtml
@page
@model Hckrieger.Pages.Posts.ManageCategoriesModel
@{
    ViewData["Title"] = "Manage Categories";
}

<h1>Manage Categories</h1>
<div class="navigation">
    <a class="btn btn-warning btn-sm" asp-page="/Categories/Index">Manage Categories</a>
    <a class="btn btn-info btn-sm" asp-page="/Posts/Index">Manage Posts</a>
</div><br />
<div class="row">
    <div class="col-6">
        <form method="post">
            <input type="hidden" asp-for="PostCategoryVM.PostCategory.PostId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostCategoryVM.PostCategory.Post.Title"></label>:
                <h4>
                    @Html.DisplayFor(m => m.PostCategoryVM.Post.Title)
                </h4>
            </div>
            <div class="form-group">
                <label asp-for="PostCategoryVM.PostCategory.Category"></label>
                @Html.DropDownListFor(m => m.PostCategoryVM.PostCategory.CategoryId, 
                                      Model.PostCategoryVM.CategoryList, 
                                      "-- Categories --", 
                                      new { @class = "form-control" })
            </div><br />
            <div class="row form-group">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary form-control">Submit</button>
                </div>
                <div class="col-6">
                    <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </form>
    </div>
    <div class="col-6" style="border-left: 3px solid black; padding-left: 25px;">
        <form method="post">
            <input type="hidden" asp-for="PostCategoryVM.Post.PostId" />


            @foreach (var item in Model.PostCategoryVM.PostCategoryList.OrderBy(m => m.Category.Name))
            {
                <div class="row mb-3">
                        <h5>
                            @item.Category.Name - <button type="submit" class="btn btn-sm btn-danger ml-2 text-right" asp-page-handler="Delete" asp-route-CategoryId="@item.CategoryId" onclick="return confirm('Are you sure you want to remove this Category?')")">Remove</button>
                        </h5>
                        
                </div>
             }

        </form>
    </div>
   
</div>

Hckrieger/Pages/Posts/ManageTags.cshtml
@page
@model Hckrieger.Pages.Posts.ManageTagsModel
@{
    ViewData["Title"] = "Manage Tags";
}

<h1>Manage Tags</h1>
<div class="navigation">
    <a class="btn btn-warning btn-sm" asp-page="/Tags/Index">Manage Tags</a>
    <a class="btn btn-info btn-sm" asp-page="/Posts/Index">Manage Posts</a>
</div>
<br />
<div class="row">
    <div class="col-6">
        <form method="post">
            <input type="hidden" asp-for="PostTagVM.PostTag.PostId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostTagVM.PostTag.Post.Title"></label>:
                <h4>
                    @Html.DisplayFor(m => m.PostTagVM.Post.Title)
                </h4>
            </div>
            <div class="form-group">
                <label asp-for="PostTagVM.PostTag.Tag"></label>
                @Html.DropDownListFor(m => m.PostTagVM.PostTag.TagId, 
                                      Model.PostTagVM.TagList, 
                                      "-- Tags --", 
                                      new { @class = "form-control" })
            </div><br />
            <div class="row form-group">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary form-control">Submit</button>
                </div>
                <div class="col-6">
                    <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </form>
    </div>
    <div class="col-6" style="border-left: 3px solid black; padding-left: 25px;">
        <form method="post">
            <input type="hidden" asp-for="PostTagVM.Post.PostId" />


            @foreach (var item in Model.PostTagVM.PostTagList.OrderBy(m => m.Tag.Name))
            {
                <div>
                        <h5>
                            @item.Tag.Name - <button type="submit" class="btn btn-sm btn-danger ml-2 text-right" asp-page-handler="Delete" asp-route-tagId="@item.TagId" onclick="return confirm('Are you sure you want to remove this tag?')")">Remove</button>
                        </h5>
                        
                </div>
             }

        </form>
    </div>
   
</div>

Hckrieger/Pages/Posts/Upsert.cshtml
@page
@model Hckrieger.Pages.Posts.UpsertModel
@if (Model.PostVM.Post == null)
{ 
    ViewData["Title"] = "Create Post";
    Layout = "/Pages/Shared/_Layout.cshtml";
} else
{
    ViewData["Title"] = "Edit Post: " + Model.PostVM.Post.Title;
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>@(Model.PostVM.Post == null ? "Create Post" : "Edit Post: " + Model.PostVM.Post.Title)</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            @if (Model.PostVM.Post != null)
            {
                <input type="hidden" asp-for="PostVM.Post.PostId" />
            }
            else
            {
                <input type="hidden" asp-for="PostVM.Post.DatePublished" value="@DateTime.Now" />
            }

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostVM.Post.Title" class="control-label"></label>:
                <input asp-for="PostVM.Post.Title" class="form-control" />
                <span asp-validation-for="PostVM.Post.Title" class="text-danger"></span>
            </div><br />

            @if (Model.PostVM.Post != null)
            {
                <div class="form-group">
                    <label asp-for="PostVM.Post.DatePublished" class="control-label"></label>
                    <input asp-for="PostVM.Post.DatePublished" asp-format="{0:yyyy-MM-ddTHH:mm}" class="form-control" />
                    <span asp-validation-for="PostVM.Post.DatePublished" class="text-danger"></span>
                </div>
            }

            <div class="form-group">
                <label asp-for="PostVM.Post.Content" class="control-label"></label>:
                <textarea id="editor" asp-for="PostVM.Post.Content" class="form-control"></textarea>
                <span asp-validation-for="PostVM.Post.Content" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value=@(Model.PostVM.Post == null ? "Create" : "Update") class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mt-1">
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}